### ISSUE TITLE
Update out of date dependencies 

### ISSUE THREAD

**Issue by jrpedrianes** [continuationlabs/nuisance#12]
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

**Comment by jrpedrianes** [comment]
Thanks for your fast response, when do you have planned to release these changes?

**Comment by cjihrig** [comment]
About a minute ago 😄. Check out v2.0.1.
