### ISSUE TITLE
Strategies continue to be called after a previous one fails

### ISSUE THREAD

**Issue by briandela** [continuationlabs/nuisance#3]
I noticed that even if a strategy fails auth, the remaining strategies are still evaluated. They are still called even though https://github.com/continuationlabs/nuisance/blob/master/lib/index.js#L33 has been hit.

Is this the desired behaviour or is the behaviour to attempt the strategies in series and then exit early if one fails?
This is the case due to `Insync.each` being used. `Insync.series` would execute them in series and fail early if one failed.

**Comment by cjihrig** [comment]
I'd take a PR for this. The docs should probably clarify the way these are checked.

**Comment by briandela** [comment]
@cjihrig Thanks for addressing this so quickly. Apologies for not getting to submitting the PR before you got to tackling it.

**Comment by cjihrig** [comment]
No problem. Glad it's taken care of.
